services:
  postgres:
    image: postgres:18.3
    container_name: flash-sale-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flash_sale_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d flash_sale_db']
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: flash-sale-rabbitmq
    hostname: flash-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: flash-sale-api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/flash_sale_db
      RABBITMQ_URL: amqp://app:app@rabbitmq:5672/
      DEV_MODE: '0'
      DIAGNOSTIC_LOGS: '1'
      OTEL_ENABLED: '1'
      OTEL_SERVICE_NAME: flash-sale-api
      OTEL_EXPORTER_OTLP_ENABLED: '0'
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
    restart: 'no'
    command: ./start-api.sh

  worker:
    build: .
    container_name: flash-sale-worker
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/flash_sale_db
      RABBITMQ_URL: amqp://app:app@rabbitmq:5672/
      DIAGNOSTIC_LOGS: '1'
      WORKER_PROCESSING_DELAY_SECONDS: '0'
      OTEL_ENABLED: '1'
      OTEL_SERVICE_NAME: flash-sale-worker
      OTEL_EXPORTER_OTLP_ENABLED: '0'
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    volumes:
      - ./:/app
    restart: 'no'
    command: ./start-worker.sh

  prometheus:
    image: prom/prometheus:v3.11.3
    container_name: flash-sale-prometheus
    depends_on:
      - api
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: 'no'

volumes:
  postgres_data:
  rabbitmq_data:
