apiVersion: v1
kind: Secret
metadata:
  name: flash-sale-secrets
  namespace: flash-sale
type: Opaque
stringData:
  POSTGRES_USER: replace-me
  POSTGRES_PASSWORD: replace-me
  RABBITMQ_DEFAULT_USER: replace-me
  RABBITMQ_DEFAULT_PASS: replace-me
